### ISSUE TITLE
Tree Shaking causes Exception

### ISSUE THREAD

**Issue by benedictstrube** [gle6as/flutter_sficon#2]
First of all: amazing package, highly needed! Thank you for taking the time!

When building for iOS in release mode and not disabling tree shaking of icons, I get the exception:

`
Error (Xcode): Target release_ios_bundle_flutter_assets failed: IconTreeShakerException: Invalid ConstFinder result. Expected "fontPackage" to be a String, "fontFamily" to be a String, and "codePoint" to be an int, got: {codePoint: 1050217, fontFamily: null, fontPackage: null, matchTextDirection: false, fontFamilyFallback: null}.
`

Any chance we can fix tree shaking to reduce the rather large font file size?

**Comment by alterhuman** [comment]
@benedictstrube were you able to fix this?

**Comment by gle6as** [comment]
Fixed and published at pub.dev
Sorry, somehow missed notification from the Github for this issue

**Comment by benedictstrube** [comment]
Thank you @gle6as! Works like a charm!
